# CMake generated Testfile for 
# Source directory: /Users/abdulaziz.alahmadi/gviz
# Build directory: /Users/abdulaziz.alahmadi/gviz/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[gvizThreadPoolTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/core/gvizThreadPoolTests")
set_tests_properties([=[gvizThreadPoolTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;220;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizVecTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/core/gvizVecTests")
set_tests_properties([=[gvizVecTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;221;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizArrayTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizArrayTests")
set_tests_properties([=[gvizArrayTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;222;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizGraphTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizGraphTests")
set_tests_properties([=[gvizGraphTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;223;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizBitArrayTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizBitArrayTests")
set_tests_properties([=[gvizBitArrayTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;224;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizDequeTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizDequeTests")
set_tests_properties([=[gvizDequeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;225;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizSubgraphTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizSubgraphTests")
set_tests_properties([=[gvizSubgraphTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;226;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizQuadtreeTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizQuadtreeTests")
set_tests_properties([=[gvizQuadtreeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;227;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizSearchTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/algorithms/search/gvizSearchTests")
set_tests_properties([=[gvizSearchTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;228;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizTreeTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/ds/gvizTreeTests")
set_tests_properties([=[gvizTreeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;229;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizEmbeddedTreeTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizEmbeddedTreeTests")
set_tests_properties([=[gvizEmbeddedTreeTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;230;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizGraphLoaderTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/utils/gvizGraphLoaderTests")
set_tests_properties([=[gvizGraphLoaderTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;231;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizGraphsTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/utils/gvizGraphsTests")
set_tests_properties([=[gvizGraphsTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;232;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizEmbeddedGraphTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizEmbeddedGraphTests")
set_tests_properties([=[gvizEmbeddedGraphTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;233;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizGRIPTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizGRIPTests")
set_tests_properties([=[gvizGRIPTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;234;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizPlanarTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizPlanarTests")
set_tests_properties([=[gvizPlanarTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;235;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizTutteTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizTutteTests")
set_tests_properties([=[gvizTutteTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;236;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizTuttePickTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizTuttePickTests")
set_tests_properties([=[gvizTuttePickTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;237;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizSpringTutteTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizSpringTutteTests")
set_tests_properties([=[gvizSpringTutteTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;238;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
add_test([=[gvizForceEmbedderTests]=] "/Users/abdulaziz.alahmadi/gviz/build-asan/tests/embedders/gvizForceEmbedderTests")
set_tests_properties([=[gvizForceEmbedderTests]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;239;add_test;/Users/abdulaziz.alahmadi/gviz/CMakeLists.txt;0;")
